### ISSUE TITLE
Stop working after 8 bag in cook off

### ISSUE THREAD

**Issue by SrMilton** [mluzarow/MethHelper#8]
self-explanation title

**Comment by Gurkoel** [comment]
Did you use it in silent or in loud mode?

**Comment by SrMilton** [comment]
Loud mode

**Comment by Gurkoel** [comment]
Pull request for a fix is set!

**Comment by THaenlein** [comment]
It stopped working after one bag at cook off for me.

**Comment by Gurkoel** [comment]
Strange, did you use the old version or mine? (latest pull request wasnt pulled yet).

**Comment by THaenlein** [comment]
My bad! I accidentally pulled from mluzarow instead of you.
I tested it on Cookoff and it worked fine.
